#!/bin/sh

delim=""

status() ( \
  date "+%b %d %H:%M"
  echo "$delim"
  battery
  echo "$delim"
  volume_control
  echo "$delim"
  brightness_control
  get_network
)

while :; do
  xsetroot -name "$(status | tr '\n' ' ')"
  sleep 1m
done
